### ISSUE TITLE
Method A-D, I | test case

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsreport#130]
In Gitlab by @gjaeger on Mar 7, 2019, 08:53 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsreport/issues/102)]

test case for method A-D and I

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Mar 23, 2019, 10:22

notes for a quick reminder:
- issue #9 - **Make Utest** - CDash like 
- issue #11 - **Add test FD** - Compare the FD of jpsreport with a reference result file
- issue #58 - **Write unit test** - Write a python script that reproduces Figures **5** and **6** in [Transitions in pedestrian fundamental diagrams of straight corridors and T-junctions](http://juser.fz-juelich.de/record/16126).
- issue #65 - **check method C** - too slow ...

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Mar 23, 2019, 16:04

CDash is a system we don't use anymore. It has been replaced by Gitlab's CI.

For the rest, I would suggest to make a directory for each of them:

```
Utest
├── test1
├── test2
└── test3
```

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Mar 25, 2019, 08:21

notes (for me):

*gitlab_ci.yml*: 
- [GitLab CI/CD Pipeline Configuration Reference](https://docs.gitlab.com/ee/ci/yaml/)

example:
```yml
#============== unit_test ============
test:
  dependencies:
    - make-linux

  stage: unit_test
  script:
    - cd build
    - ctest -R Boost
    - ctest -R clean
  tags:
    - linux

```

*structure*: 
- see folder [Utest](https://gitlab.version.fz-juelich.de/jupedsim/jpscore/tree/develop/Utest) in jpscore
